### ISSUE TITLE
please update npm to v3.0

### ISSUE THREAD

**Issue by slimtom95** [fin-hypergrid/datasaur-filter#1]
Package `datasaur-filter` on npm is at version 1.01, please make an update to version 3.0

p.s. The other 3 datasaur-* plugins are at version 3.0, checked.

@joneit Thanks!

**Comment by joneit** [comment]
Thanks for the nudge. I published it to npm last week as `3.0.0` — however, I just updated it to `3.0.1` because I realized the dependency on `datasaur-indexed` was still set to install from github. It now installs from npm.

It shouldn't have mattered so long as all dependencies were using the same version. I recommend a clean `npm install` to make sure your project ends up with just this latest version `3.0.1` (and not both `3.0.0` and `3.0.1` which may cause issues).
